#spring:
#    datasource:
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://localhost:3306/ds0?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
#        username: root
#        password: 'root'
server:
    port: 8088

spring:
    shardingsphere:
        props:
            sql:
                show: true
        datasource:
            ds0:
                type: com.zaxxer.hikari.HikariDataSource
                driver-class-name: com.mysql.cj.jdbc.Driver
                jdbc-url: jdbc:mysql://localhost:3306/ds0?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
                username: root
                password: 'root'
            names: ds0
        sharding:
            tables:
                t_order:
                    actual-data-nodes: ds0.t_order$->{0..1}
                    table-strategy:
                        inline:
                            algorithm-expression: t_order$->{order_id % 2}
                            sharding-column: order_id

mybatis:
    mapper-locations: classpath:mapper/*.xml